### ISSUE TITLE
Skids

### ISSUE THREAD

**Issue by Sn8ow** [Its-Vichy/Antiskidware#1]
Good skids
https://github.com/sheep-o/Windows-MBR-Overwrite

**Comment by Its-Vichy** [comment]
Haha, i have put il of my ref in the readme [here](https://github.com/Its-Vichy/Antiskidware/blob/main/README.md?plain=1).
But, why do you say skid when you forke all my repos, remove the credit say "omg look at my code" ? hahah.
Skid says skid lmao, you are just my biggest fanboy.
